from .hypothes_1 import HypothesCorrelation
from .hypothes_2 import HypothesDaysPercents
from .hypothes_3 import HypothesExtSources
from .hypothes_4 import HypothesDocuments
from .hypothes_5 import HypothesCredit
from .hypothes_6 import HypothesSocialCircle
from .hypothes_7 import HypothesWorkingHours
from .hypothes_8 import HypothesBadCar
from .hypothes_9 import HypothesContactsNumber
from .hypothes_10 import HypothesFamilyStatus
from .only_good_hypotheses import OnlyGoodHypotheses